### ISSUE TITLE
[doc] How to configure for NativeWind

### ISSUE THREAD

**Issue by jbtheard** [storybookjs/addon-react-native-web#45]
[NativeWind](https://www.nativewind.dev/overview/) allows to use tailwind css across platforms, leveraging react-native Stylesheet for mobile and acting as a compatibility layer with Tailwind on web. It's a replacement to tailwinds-react-native and is used in more and more projects such as Solito for their [Tailwind starter kit](https://solito.dev/tailwind).

As we test components across platforms, a guide on how to implement it for Storybook would come handy

**Comment by jbtheard** [comment]
Oh I didn't identify that one in my search. I'll have a look at it first. Thanks for pointing at it.
(and thanks for this package)

**Comment by kimchouard** [comment]
Alright, reviving this thread since I can't get @dannyhw's [expo-template-storybook](https://github.com/dannyhw/expo-template-storybook) to work with [NativeWind](https://www.nativewind.dev/v4/getting-started/expo-router). 😬

Here's a boilerplate I'm trying to put together: [expo-nativewind-template-storybook](https://github.com/kimchouard/expo-nativewind-template-storybook) 👨🏼‍🍳

👉 It works great with `yarn storybook`, both on native and web (styles are properly picked up)
❗️ BUT fails with `yarn storybook` (using the [React Native Web Addon](https://storybook.js.org/addons/@storybook/addon-react-native-web#react-native-web-addon-for-storybook) through webpack) with this error:

![CleanShot 2024-02-07 at 16 08 08@2x](https://github.com/storybookjs/addon-react-native-web/assets/2856923/5d67e825-31ce-49d5-a84d-a4850ff64874)

Here's my `.storybook/main.js` config:
```js
import path from 'path';

/** @type{import("@storybook/react-webpack5").StorybookConfig} */
module.exports = {
  stories: [
    "../components/**/*.stories.mdx",
    "../components/**/*.stories.@(js|jsx|ts|tsx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    {
      name: '@storybook/addon-react-native-web',
      options: {
        modulesToTranspile: [
          'nativewind',
          // 'react-native-css-interop', // Needed?
          'react-native-reanimated',
        ],
        babelPlugins: [
          '@babel/plugin-proposal-export-namespace-from',
          'react-native-reanimated/plugin',
          // 👇 This is what makes it crash 👇 
          'nativewind/babel', 
        ],
      },
    },
  ],
  framework: {
    name: "@storybook/react-webpack5",
    options: {},
  },
  docs: {
    autodocs: true,
  },
  webpackFinal: async (config, { configType }) => {
    config.module.rules.push({
      test: /\.css$/,
      use: [
        {
          loader: 'postcss-loader',
          options: {
            postcssOptions: {
              plugins: [require('tailwindcss'), require('autoprefixer')]
            }
          }
        }
      ],
      include: path.resolve(__dirname, '../')
    })

    return {
      ...config
    }
  }
};
```

Feel free to [clone the repo](https://github.com/kimchouard/expo-nativewind-template-storybook) and test for yourself! Looking forward to get your take on this @dannyhw 🤔 Thanks for all your work to date to bring Storybook to the RN community 🙌🏻

**Notes:**
- Based on the [example shared](https://github.com/dohomi/nativewind-solito-kitchen-sink/blob/master/apps/storybook-react/.storybook/main.ts) on earlier on this thread, I had to install `postcss-loader` and `autoprefixer` too, to make the `webpackFinal` script to run.
- Nativewind v4 is tailored to `Metro` whereas the web-only Storybook is using `webpack`.
- When configuring your `metro.config.js` file, you need to add a wrapper with `withNativeWind(config, { input: './global.css' });`. How is that done with webpack?

**Comment by dannyhw** [comment]
You should import global css in your preview.js but i can take a look

**Comment by dannyhw** [comment]
@kimchouard "nativewind/babel" is a preset and not a plugin thats why you get that error

**Comment by dannyhw** [comment]
update to 0.0.23 and this kind of config should work

```
const path = require('path');

/** @type{import("@storybook/react-webpack5").StorybookConfig} */
export default {
  stories: [
    '../stories/**/*.stories.mdx',
    '../stories/**/*.stories.@(js|jsx|ts|tsx)', // your path here
  ],
  addons: [
    {
      name: '@storybook/addon-react-native-web',
      options: {
        modulesToTranspile: [
          'react-native-reanimated',
          'nativewind',
          'react-native-css-interop',
        ],
        babelPresets: ['nativewind/babel'],
        babelPresetReactOptions: { jsxImportSource: 'nativewind' },
        babelPlugins: [
          'react-native-reanimated/plugin',
        ],
      },
    },
    '@storybook/addon-essentials',
  ],
  framework: {
    name: '@storybook/react-webpack5',
    options: {},
  },
  webpackFinal: async (config) => {
    config.module?.rules?.push({
      test: /\.css$/,
      use: [
        {
          loader: 'postcss-loader',
          options: {
            postcssOptions: {
              plugins: [require('tailwindcss'), require('autoprefixer')],
            },
          },
        },
      ],
      include: [
        path.resolve(__dirname, '../'), // path to project root
      ],
    });

    return config,
  },
};
```

**Comment by dannyhw** [comment]
there should be a way to make this work with the storybook styling addon instead of adding a postcss-loader manually but I haven't got around to trying that out

**Comment by dannyhw** [comment]
There is also now a nativewind setup in this repo if you want to see a working setup

**Comment by kimchouard** [comment]
@dannyhw YOU'RE THE MAN!!! 🙌🏻

FYI, I got it to work but I had to add an extra babelPlugin:
```ts
        babelPlugins: [
          // (...)
          [
            '@babel/plugin-transform-react-jsx',
            {
              runtime: 'automatic',
              importSource: 'nativewind',
            },
          ],
        ],
```

Not sure what's different in your example that makes it work without this plugin configuration? 🤷🏼‍♂️

**Comment by kimchouard** [comment]
I've updated the [expo-nativewind-template-storybook](https://github.com/kimchouard/expo-nativewind-template-storybook/tree/main) boilerplate to match.

@dannyhw I think you can safely close this issue now. :)

Merci!

**Comment by kimchouard** [comment]
Since this issue is called `[doc] ...`, I've created #85 to add the working config to the doc. :)

**Comment by dannyhw** [comment]
I believe this is now completed, please let me know if more information is needed and you want to reopen.
