### ISSUE TITLE
react native vector icons do not show [Bug]

### ISSUE THREAD

**Issue by grinono** [storybookjs/addon-react-native-web#51]
I'm trying to see /react-native-vector-icons in storybook

I run storybook react native web with webpack5 config.

```
 core: {
    builder: 'webpack5',
  },
```

### Steps to reproduce the behavior

i added the following code to the .storybook/main.js file
```{
      name: '@storybook/addon-react-native-web',
      options: {
        modulesToTranspile: ['react-native-vector-icons'],
      },
    },
```

When loading a story with an icon from 
```
import Entypo from "react-native-vector-icons/Entypo";

   <Entypo name={name} size={18} style={{ color: iconColor }} />
```

i get a square box

<img width="79" alt="Screenshot 2023-02-01 at 11 23 35" src="https://user-images.githubusercontent.com/4255206/216016977-73208b1d-5cd4-4b06-a1c4-79d1a6815c18.png">

Does anyone know how to fix this?

**Comment by dannyhw** [comment]
@grinono you need to add the fonts otherwise it won't have anything to show, see the [vector icons readme](https://github.com/oblador/react-native-vector-icons#web-with-webpack) I also have a working example [here](https://github.com/dannyhw/addon_react_native_web_example/tree/main/.storybook) the example is a bit old but the same thing should still work.

**Comment by grinono** [comment]
yes, i saw the configs like that, but we are using webpack5 requires other config to enable vector icons. We switch the expo icons. that works fine :-)

**Comment by dannyhw** [comment]
Ok then since you don't have the problem anymore I will close this issue 👍
